### ISSUE TITLE
I get these errors when I download from springer. Please tell me how to resolve them.

### ISSUE THREAD

**Issue by shanksghub** [JnyJny/springer_downloader#7]

**Comment by shanksghub** [comment]
You can download books from https://drive.google.com/drive/u/0/folders/1fD1csbKVIdfKvzLoLbIjnryae1u995YQ here.

**Comment by JnyJny** [comment]
Springer has revised the `en-all` collections URL and contains a reduced number of books. I'll update the tool with the revised URL.

**Comment by JnyJny** [comment]
Ok, version 0.17.0 is published to PyPI with the corrected URLs, all other URLs (de-all, de-med)  are correct as of today. Update your installed version of springer and it should work as designed.
